{
 "title": "App Engine",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "Data source", "query": "prometheus" },
   {
    "name": "Pod",
    "query": {
     "query": "label_values(kube_pod_info, pod)"
    }
   },
   { "name": "Host", "query": { "query": "label_values(host)" } },
   {
    "name": "rabbitmq_cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(rabbitmq_identity_info{},cluster)"
    }
   },
   {
    "name": "rabbitmq_job",
    "label": "Job",
    "query": {
     "query": "label_values(rabbitmq_identity_info{},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "App Engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Error  HTTP GET/PUT/POST Request ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(( sum (http_requests_total{method=\"GET\",host=\"$Host\",scheme=\"http\"})  ) / (   sum (http_requests_total{method=\"GET\",host=\"$Host\",scheme=\"http\"}) - (sum (http_requests_total{status_class=\"client-error\",method=\"GET\",host=\"$Host\",scheme=\"http\"}) + sum (http_requests_total{status_class=\"server-error\",method=\"GET\",host=\"$Host\",scheme=\"http\"}) ) )  - 1 ) * 100",
     "legendFormat": "Total Error GET"
    },
    {
     "expr": "( sum (http_requests_total{method=\"PUT\",host=\"$Host\",scheme=\"http\", job=\"astarte/astarte-appengine-api\"}) / (sum (http_requests_total{method=\"PUT\",host=\"$Host\",scheme=\"http\", job=\"astarte/astarte-appengine-api\"}) - (sum (http_requests_total{status_class=\"client-error\", method=\"PUT\",host=\"$Host\",scheme=\"http\", job=\"astarte/astarte-appengine-api\"}))) - 1) * 100 ",
     "legendFormat": "Total Error PUT"
    },
    {
     "expr": "( sum (http_requests_total{method=\"POST\",host=\"$Host\",scheme=\"http\", job=\"astarte/astarte-appengine-api\"}) / (sum (http_requests_total{method=\"POST\",host=\"$Host\",scheme=\"http\", job=\"astarte/astarte-appengine-api\"}) - (sum (http_requests_total{status_class=\"client-error\", method=\"POST\",host=\"$Host\",scheme=\"http\", job=\"astarte/astarte-appengine-api\"}))) - 1) * 100 ",
     "legendFormat": "Total Error POST"
    }
   ]
  },
  {
   "title": "Total Messages Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum (sent_messages_total{realm=\"zpe\"})",
     "legendFormat": "Total Messages Sent"
    }
   ]
  },
  {
   "title": "Process Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "process_threads_total{job=\"astarte/astarte-appengine-api\"}",
     "legendFormat": "Instance: {{instance}} Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "App Engine Database Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "appengine_api_database_health",
     "legendFormat": "Instance: {{instance}} Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "App Engine API sent messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sent_messages_total{job=\"astarte/astarte-appengine-api\"}",
     "legendFormat": "Instance: {{instance}} Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "App Engine process virtual memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"astarte/astarte-appengine-api\"}",
     "legendFormat": "Instance: {{instance}} Pod: {{pod}}"
    }
   ]
  }
 ]
}