{
 "title": "RabbitMQ",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "Data source", "query": "prometheus" },
   {
    "name": "Pod",
    "query": {
     "query": "label_values(kube_pod_info, pod)"
    }
   },
   { "name": "Host", "query": { "query": "label_values(host)" } },
   {
    "name": "rabbitmq_cluster",
    "label": "Rabbitmq_cluster",
    "query": {
     "query": "label_values(rabbitmq_identity_info{},cluster)"
    }
   },
   {
    "name": "rabbitmq_job",
    "label": "Rabbitmq_job",
    "query": {
     "query": "label_values(rabbitmq_identity_info{},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "RabbitMQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ready Messages",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready * on(instance) group_left(cluster) rabbitmq_identity_info{cluster=\"$rabbitmq_cluster\", job=\"$rabbitmq_job\"})"
    }
   ]
  },
  {
   "title": "Incoming messages / s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_published_total[60s]) * on(instance) group_left(cluster) rabbitmq_identity_info{cluster=\"$rabbitmq_cluster\", job=\"$rabbitmq_job\"})"
    }
   ]
  },
  {
   "title": "Publishers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_channels * on(instance) group_left(cluster) rabbitmq_identity_info{cluster=\"$rabbitmq_cluster\", job=\"$rabbitmq_job\"}) - sum(rabbitmq_channel_consumers * on(instance) group_left(cluster) rabbitmq_identity_info{cluster=\"$rabbitmq_cluster\", job=\"$rabbitmq_job\"})"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_connections * on(instance) group_left(cluster) rabbitmq_identity_info{cluster=\"$rabbitmq_cluster\", job=\"$rabbitmq_job\"})"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queues * on(instance) group_left(cluster) rabbitmq_identity_info{cluster=\"$rabbitmq_cluster\", job=\"$rabbitmq_job\"})"
    }
   ]
  },
  {
   "title": "Unacknowledged messages",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_unacked * on(instance) group_left(cluster) rabbitmq_identity_info{cluster=\"$rabbitmq_cluster\", job=\"$rabbitmq_job\"})"
    }
   ]
  },
  {
   "title": "Outgoing messages / s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_redelivered_total[60s]) * on(instance) group_left(cluster) rabbitmq_identity_info{cluster=\"$rabbitmq_cluster\", job=\"$rabbitmq_job\"}) +\nsum(rate(rabbitmq_channel_messages_delivered_total[60s]) * on(instance) group_left(cluster) rabbitmq_identity_info{cluster=\"$rabbitmq_cluster\", job=\"$rabbitmq_job\"}) +\nsum(rate(rabbitmq_channel_messages_delivered_ack_total[60s]) * on(instance) group_left(cluster) rabbitmq_identity_info{cluster=\"$rabbitmq_cluster\", job=\"$rabbitmq_job\"}) +\nsum(rate(rabbitmq_channel_get_total[60s]) * on(instance) group_left(cluster) rabbitmq_identity_info{cluster=\"$rabbitmq_cluster\", job=\"$rabbitmq_job\"}) +\nsum(rate(rabbitmq_channel_get_ack_total[60s]) * on(instance) group_left(cluster) rabbitmq_identity_info{cluster=\"$rabbitmq_cluster\", job=\"$rabbitmq_job\"})"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_channel_consumers * on(instance) group_left(cluster) rabbitmq_identity_info{cluster=\"$rabbitmq_cluster\", job=\"$rabbitmq_job\"})"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_channels * on(instance) group_left(cluster) rabbitmq_identity_info{cluster=\"$rabbitmq_cluster\", job=\"$rabbitmq_job\"})"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_build_info * on(instance) group_left(cluster) rabbitmq_identity_info{cluster=\"$rabbitmq_cluster\", job=\"$rabbitmq_job\"})"
    }
   ]
  },
  {
   "title": "RabbitMQ Message Queue ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (job) (rabbitmq_queue_messages{})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RabbitMQ process resident memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rabbitmq_process_resident_memory_bytes",
     "legendFormat": "Service: {{service}} Instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Messages ready to be delivered to consumers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready * on(instance) group_left(cluster, rabbitmq_node) rabbitmq_identity_info{cluster=\"$rabbitmq_cluster\", job=\"$rabbitmq_job\"}) by(rabbitmq_node)",
     "legendFormat": "Messages ready to be delivered"
    }
   ]
  }
 ]
}