{
 "title": "VerneMQ",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Pod",
    "query": {
     "query": "label_values(kube_pod_info, pod)"
    }
   },
   { "name": "Host", "query": { "query": "label_values(host)" } },
   {
    "name": "rabbitmq_cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(rabbitmq_identity_info{},cluster)"
    }
   },
   {
    "name": "rabbitmq_job",
    "label": "Job",
    "query": {
     "query": "label_values(rabbitmq_identity_info{},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "VerneMQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connected Clients",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "(socket_open - socket_close)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Queue processes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "queue_processes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "VerneMQ Node Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_wallclock", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Erlang VM Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_utilization", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Current MQTT Receive Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mqtt_publish_received[30s]))"
    }
   ]
  },
  {
   "title": "Current MQTT send rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mqtt_publish_sent[30s]))"
    }
   ]
  },
  {
   "title": "Connect/Disconnect Rate (per second)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(socket_open[30s])",
     "legendFormat": "Connect (Socket Open) - Instance: {{instance}} Pod: {{pod}}"
    },
    {
     "expr": "rate(socket_close[30s])",
     "legendFormat": "Disconnect (Socket Closed) - Instance: {{instance}} Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Current Queue Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "queue_processes{job=\"astarte/astarte-vernemq\"}",
     "legendFormat": "Instance: {{instance}} Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Queue Setup and Teardown Rate (per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(queue_setup[60s])",
     "legendFormat": "Queue Setup - Instance: {{instance}} Pod: {{pod}}"
    },
    {
     "expr": "rate(queue_teardown[60s])",
     "legendFormat": "Queue Teardown - Instance: {{instance}} Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Messages in Queues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(queue_message_in[1m])",
     "legendFormat": "In - Instance: {{instance}} Pod: {{pod}}"
    },
    {
     "expr": "rate(queue_message_out[1m])",
     "legendFormat": "Out - Instance: {{instance}} Pod: {{pod}}"
    },
    {
     "expr": "rate(queue_message_drop[1m])",
     "legendFormat": "Drop - Instance: {{instance}} Pod: {{pod}}"
    },
    {
     "expr": "rate(queue_message_unhandled[1m])",
     "legendFormat": "Unhandled - Instance: {{instance}} Pod: {{pod}}"
    }
   ]
  }
 ]
}