{
 "title": "Data Updater Plant",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "Data source", "query": "prometheus" },
   {
    "name": "Pod",
    "query": {
     "query": "label_values(kube_pod_info, pod)"
    }
   },
   { "name": "Host", "query": { "query": "label_values(host)" } },
   {
    "name": "rabbitmq_cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(rabbitmq_identity_info{},cluster)"
    }
   },
   {
    "name": "rabbitmq_job",
    "label": "Pod",
    "query": {
     "query": "label_values(rabbitmq_identity_info{},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Data updater plant", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage (Process/second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"astarte/astarte-data-updater-plant\"}",
     "legendFormat": "Instance: {{instance}} Kind: {{kind}} Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Detected crashes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "detected_crashes_total{job=\"astarte/astarte-data-updater-plant\"}",
     "legendFormat": "Instance: {{instance}} Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Device Connections/Disconnections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "device_connections_total{job=\"astarte/astarte-data-updater-plant\"}",
     "legendFormat": "Connections in {{instance}}"
    },
    {
     "expr": "device_disconnections_total{job=\"astarte/astarte-data-updater-plant\"}",
     "legendFormat": "Disconnections in {{instance}}"
    }
   ]
  },
  {
   "title": "Connected Devices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "connected_devices{job=\"astarte/astarte-data-updater-plant\"}",
     "legendFormat": "Instance: {{instance}} Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Process Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "process_threads_total{job=\"astarte/astarte-data-updater-plant\"}",
     "legendFormat": "Instance: {{instance}} Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Processed Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "processed_messages_total{job=\"astarte/astarte-data-updater-plant\"}",
     "legendFormat": "Instance: {{instance}} Interface: {{interface_type}} Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Published Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "published_events_total{job=\"astarte/astarte-data-updater-plant\"}",
     "legendFormat": "Instance: {{instance}} Event: {{topic}} Pod: {{pod}}"
    }
   ]
  }
 ]
}