package models

type Dashboard struct {
	ID          int    `json:"id"`
	UID         string `json:"uid"`
	Version     int    `json:"version"`
	Title       string `json:"title"`
	Description string `json:"description"`
	URL         string `json:"url"`
}

type DashboardResponse struct {
	ID      int    `json:"id"`
	UID     string `json:"uid"`
	URL     string `json:"url"`
	Status  string `json:"status"`
	Version int    `json:"version"`
}

type AutoGenerated struct {
	Meta struct {
		URL string `json:"url"`
	} `json:"meta"`
	Dashboard struct {
		ID          int    `json:"id"`
		UID         string `json:"uid"`
		Version     int    `json:"version"`
		Title       string `json:"title"`
		Description string `json:"description"`
		URL         string `json:"url"`
	} `json:"dashboard"`
}

type AutoGeneratedResponse struct {
	ID    int    `json:"id"`
	UID   string `json:"uid"`
	Title string `json:"title"`
	URL   string `json:"url"`
}
